# Generated by Django 5.2.1 on 2025-05-22 20:30

import analysis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=analysis.models.article_upload_to)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], help_text='Language chosen by the user (used for the interface and prompts)', max_length=2)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Datafication score (0–10) indicating the density of structured data')),
                ('profile_label', models.CharField(help_text="Short label describing the data profile (e.g. 'Low potential', 'High potential')", max_length=50)),
                ('summary', models.TextField(blank=True, help_text='Optional AI-generated summary of the article content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the analysis was generated')),
                ('article', models.OneToOneField(help_text='The article this analysis refers to', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analysis.article')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
