# Generated by Django 5.2.1 on 2025-05-22 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('analysis', models.ForeignKey(help_text='Analysis from which this angle was generated', on_delete=django.db.models.deletion.CASCADE, related_name='angles', to='analysis.analysis')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='DatasetSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=20)),
                ('found_by', models.CharField(choices=[('LLM', 'Generated by LLM'), ('CONNECTOR', 'Found via API connector')], max_length=10)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PER', 'Person'), ('ORG', 'Organization'), ('LOC', 'Location'), ('DATE', 'Date'), ('NUM', 'Number'), ('MISC', 'Misc')], max_length=4)),
                ('value', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True, help_text='Sentence excerpt', null=True)),
                ('analysis', models.ForeignKey(help_text='The analysis that produced this entity', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='VisualizationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('markdown_snippet', models.TextField(blank=True, help_text='Optional pre-formatted markdown for the front-end', null=True)),
                ('angle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='analysis.angle')),
            ],
        ),
    ]
