# Generated by Django 5.2.1 on 2025-06-14 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_angle_datasetsuggestion_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetsuggestion',
            name='formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='datasetsuggestion',
            name='last_modified',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datasetsuggestion',
            name='licence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasetsuggestion',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasetsuggestion',
            name='richness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
