# Generated by Django 5.2.1 on 2025-06-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_datasetsuggestion_formats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsuggestion',
            name='source',
            field=models.CharField(max_length=200),
        ),
    ]
