# Generated by Django 5.2.1 on 2025-06-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_datasetsuggestion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='angle_ressources',
            field=models.JSONField(blank=True, default=list, help_text='JSON object containing the angle resources'),
        ),
    ]
