# Generated by Django 5.2.1 on 2025-06-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysis_angle_ressources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='angle_ressources',
            new_name='angle_resources',
        ),
    ]
