# Generated by Django 5.2.1 on 2025-08-20 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_rename_angle_ressources_analysis_angle_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='angle',
            name='topic',
            field=models.CharField(blank=True, help_text='Topic/theme for mapping to dataset tags', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasetsuggestion',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Tags for mapping to angle topics', size=None),
        ),
    ]
