"""
Django settings for datascope_backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from datetime import timedelta
import os

# (Option simple) charger .env si ce n'est pas déjà fait
try:
    from dotenv import load_dotenv  # pip install python-dotenv
    BASE_DIR = Path(__file__).resolve().parent.parent
    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Clés & config recherche web ---
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY", "")

SEARCH_ENABLED = True
SEARCH_PROVIDER = os.getenv("SEARCH_PROVIDER", "tavily")  # tavily | serper | bing | searxng
SEARCH_MAX_RESULTS = int(os.getenv("SEARCH_MAX_RESULTS", "10"))
SEARCH_TIMEOUT = int(os.getenv("SEARCH_TIMEOUT", "8"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = config('SECRET_KEY', default='dev-secret-key-for-ci')
SECRET_KEY = config('SECRET_KEY')



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analysis',
    'api',
    'users',
    'rest_framework',
    'rest_framework.authtoken',  # To using later
    'rest_framework_simplejwt',
    'ai_engine',
    'corsheaders',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # dev
        "rest_framework.authentication.TokenAuthentication",    # prod/JWT après
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
]

ROOT_URLCONF = 'datascope_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'datascope_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME":     config("DB_NAME"),
        "USER":     config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST":     config("DB_HOST", default="127.0.0.1"),
        "PORT":     config("DB_PORT", default="5432"),
    }
}

if os.getenv("USE_SQLITE_FOR_TESTS"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "users.User"

# --- Playground flag
PLAYGROUND_DEBUG_MODE = os.getenv("PLAYGROUND_DEBUG_MODE", "0") in ("1", "true", "True")

# --- Logging dédié playground
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "playground_file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "playground.log"),
            "mode": "a",
        },
    },
    "loggers": {
        "playground": {
            "handlers": ["console", "playground_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# URL_VALIDATION_TIMEOUT: Maximum delay in seconds before a URL validation request is aborted
URL_VALIDATION_TIMEOUT = 5

# URL_VALIDATION_USER_AGENT: Identification string sent in HTTP header during URL validation
URL_VALIDATION_USER_AGENT = "DatascopeAI/validator"

# URL_VALIDATION_FILTER_404: If True, filters URLs returning a 404 error (page not found)URL_VALIDATION_FILTER_404 = True
URL_VALIDATION_FILTER_404 = True 

URL_VALIDATION_DEFAULT = True


TRUSTED_DOMAINS = [
    # FR/EU
    "data.gouv.fr", "insee.fr", "ec.europa.eu", "eurostat.ec.europa.eu",
    "santepubliquefrance.fr", "ecdc.europa.eu",
    # INTL
    "oecd.org", "who.int", "worldbank.org", "imf.org", "un.org", "unesco.org",
    # EN (US/UK)
    "data.gov", "cdc.gov", "data.gov.uk", "ons.gov.uk", "nhs.uk",
]
TRUSTED_SOFT_WEIGHT = 0.15
TRUSTED_STRICT_DEFAULT = False

THEME_FILTER_SOFT_PENALTY = 0.15    # pénalité multiplicative si hors-thème (soft)
THEME_FILTER_STRICT_DEFAULT = False # strict = drop hors-thème
THEME_FILTER_MIN_UNIGRAM_HITS = 2   # seuil pragmatique

CONNECTORS_ENABLED = False  # ← par défaut OFF pour cette version
DATASCOPE_LOG_LEVEL = "WARNING"  # "DEBUG" pour activer les traces locales

HOMEPAGE_SOFT_PENALTY = 0.20  # 0.25–0.30 si tu veux appuyer l'effet

SOURCE_MIN_PER_ANGLE = 3
DATASETS_MIN_PER_ANGLE = 3

# settings (exemples)
HOMEPAGE_SOFT_PENALTY = 0.35
THEME_FILTER_STRICT_FOR_DATASETS = True  # stricte sur la passe datasets

# back-off (utilisé seulement si datasets<3)

SEARCH_BACKOFF_DEPTH = "advanced"
SEARCH_RESULTS_PER_ANGLE = 7  # donner un peu plus de matière puis couper au reranking

# ranking weights (safe defaults)
DATASET_FORMAT_BOOST = 0.25
DATASET_PATH_BOOST = 0.15
PDF_SOFT_PENALTY = 0.20
DATASET_ROOT_LISTING_PENALTY = 0.15
# déjà présent : HOMEPAGE_SOFT_PENALTY (vous l'avez monté à ~0.35)


